version: '3'
services:
    ngircd:
        build:
            context: ngircd
        container_name: ngircd
        ports:
            - "6667:6667"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./ngircd:/usr/local/etc
        #restart: always
